config/routes.rb
Cuptastic::Application.routes.draw do
  root to: "home#index"
  scope :api do
    get "/videos" => "videos#index"
    get "/videos/:id" => "videos#show"
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, presence: true
  validates :link, presence: true
  validates :team, presence: true


  def self.make_api_call(team = " ")
    world_cup_videos = []

    client = YouTubeIt::Client.new(:dev_key=>YOUTUBE_CLIENT_ID)
    video = client.videos_by(:query => "2014 world cup " + team.to_s, :duration =>  "long", :categories => [:sports], :tags => ['soccer', 'football'], :page => 1, :per_page => 50, :orderby => 'duration')

    video.videos.each do |vid|
      if vid.title != nil
        title = vid.title
      else
        title = ""
      end

      if vid.description != nil
        summary = vid.description
      else
        summary = ""
      end

      if vid.duration != nil
        duration = vid.duration
      else
        duration = ""
      end

      if vid.media_content[0].url !=nil
        link = vid.media_content[0].url
      else
        link = ""
      end

      if vid.published_at !=nil
        published_at = vid.published_at
      else
        published_at = ""
      end

      world_cup_videos << Video.new(title: title, summary: summary, duration: duration, link: link, published_at: published_at, team: " ")
    end
    return world_cup_videos
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    if params[:q]
      render json: Video.make_api_call(params[:q])
    else
      render json: Video.make_api_call
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<div ng-controller="VideoCtrl">
  <div id="header">
    <p>Cuptastic</p>
    <section>
   <!--    <%=form_for :q, url: videos_path, method: :get do |f|%>
      <%=f.select :team, collection: ['Brazil', 'Argentina', 'Spain', 'Chile']%>
      <ng-click="updateVid()" value="New Team"><%=f.submit 'Select Team'%>
      <%end%> -->

      <!-- <select ng-model="teams" ng-options="team.name group by team.group for team in teams" value="worldcup"></select> -->
      <world-cup-teams update="newVideo(team)"></world-cup-teams>
    </section>



  </div>

  <div id="video-list-container">
  <ul>
    <input ng-model="query.title" placeholder="Search videos">
    <li ng-repeat="video in videos |filter:query" ng-click="showVideo(video, $index)">
      <h1 ng-class="{active: $index == selectedRow}">{{video.title}}</h1>
    </li>
  </ul>
  </div>

  <div id="video-view-container" ng-show="selectedVideo">
    <h2>{{selectedVideo.title}}</h2>
    <iframe ng-src="{{selectedVideoURL}}"></iframe>
    <p>{{selectedVideo.summary}}</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="WorldCup">
<head>
  <title>Cuptastic</title>
  <%= stylesheet_link_tag    "application", media: "all" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular-resource.min.js"></script>
<%= javascript_include_tag "application" %>
</body>
</html>